# Generated by Django 6.0.4 on 2026-04-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='available_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='counselor',
            name='expertise',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='counselor',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='counselor',
            name='progress',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='counselor',
            name='therapy_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counselor',
            name='video_duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
