# Generated by Django 6.0.4 on 2026-04-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0002_counselor_available_slots_counselor_expertise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselor',
            old_name='specialization',
            new_name='title',
        ),
    ]
