# Generated by Django 6.0.4 on 2026-04-29 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0003_rename_specialization_counselor_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='date',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(default='mon', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='9999999999', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='na', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='NilaApp.counselor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default='mon'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default='09:00'),
        ),
    ]
