# Generated by Django 6.0.4 on 2026-05-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0004_remove_availability_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(default='8:00'),
        ),
        migrations.AddField(
            model_name='availability',
            name='session_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
    ]
