# Generated by Django 6.0.4 on 2026-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
