# Generated by Django 6.0.4 on 2026-05-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0011_alter_booking_payment_status_alter_booking_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='phone',
            new_name='email',
        ),
    ]
