# Generated by Django 6.0.4 on 2026-05-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0012_rename_phone_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mode',
            field=models.CharField(choices=[('Video Call', 'Video Call'), ('phone-Call', 'phone-Call'), ('In-Person', 'In-Person')], default='Video Call', max_length=20),
        ),
    ]
