# Generated by Django 6.0.4 on 2026-05-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0013_alter_booking_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
