# Generated by Django 6.0.4 on 2026-05-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0014_alter_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='counselor_name',
            field=models.CharField(default='Den', max_length=50),
        ),
    ]
