# Generated by Django 6.0.4 on 2026-05-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0015_booking_counselor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='counselor_name',
            field=models.CharField(default='Den', max_length=50),
        ),
    ]
