# Generated by Django 6.0.4 on 2026-05-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0016_availability_counselor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='counselor_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
