# Generated by Django 6.0.4 on 2026-05-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0017_alter_availability_counselor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
    ]
