# Generated by Django 6.0.4 on 2026-05-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0021_alter_booking_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='street',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
