# Generated by Django 6.0.4 on 2026-05-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NilaApp', '0023_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mode',
            field=models.CharField(choices=[('Video-Call', 'Video-Call'), ('Phone-Call', 'Phone-Call'), ('In-Person', 'In-Person')], default='Video-Call', max_length=20),
        ),
    ]
